### ISSUE TITLE
Errors obtained during the run of the simulation example of octomap_mapping_planning

### ISSUE THREAD

**Issue by dorian21b** [ctu-mrs/mrs_octomap_mapping_planning#10]
Hello
I am having a problem running simulation_example from octomap_mapping_planning. I have the native installation (not recommended), I did the tutorials (https://ctu-mrs.github.io/docs/software/catkin/managing_workspaces/managing_workspaces.html) for sourcing the octomap_workspace and for extending the workspaces following the recommended hierarchy. 

I also followed the steps from "Backward incompatibility: [Updates for px4 firmware v1.13.2 #150.](https://github.com/ctu-mrs/mrs_uav_system/issues/150)

However, when I run the simulation:

cd ~/octomap_workspace/src/octomap_planning/tmux/simulation_example
./start.sh

Gazebo open and the uav takes off but I have the following errors on the tmux sessions:  gazebo, mapplan and easy control 

![Screenshot from 2023-06-08 10-54-26](https://github.com/ctu-mrs/octomap_mapping_planning/assets/131147954/abae0b7d-29e1-46c9-857d-cc46bb923625)

![Screenshot from 2023-06-08 10-54-35](https://github.com/ctu-mrs/octomap_mapping_planning/assets/131147954/c9ee5abd-aec7-4756-865d-a879ac7ff0a3)

![Screenshot from 2023-06-08 10-54-44](https://github.com/ctu-mrs/octomap_mapping_planning/assets/131147954/69de7053-3dbb-48e8-95e4-04f7f00a658c)

Thank you for your time

**Comment by dorian21b** [comment]
Hello
Thank you for your answer, I am using the last commit of the  `octomap_mapping_planning` repository.

![Screenshot from 2023-06-20 14-45-20](https://github.com/ctu-mrs/octomap_mapping_planning/assets/131147954/993d34c7-5cb8-440a-b76f-ecb0e3d305c2)

![Screenshot from 2023-06-20 14-46-44](https://github.com/ctu-mrs/octomap_mapping_planning/assets/131147954/7c5d8239-664e-4a73-8940-0e847af7e955)

**Comment by pritzvac** [comment]
That looks correct. Do you have Ubuntu 20.04? Did you do a clean install or have you already had the MRS system installed for some time, since you were doing the steps from the backwards incompatibility issue?

Try to also run `git pull` in `uav_modules` to get the latest commit there (if you don't have it), re-run the installation script in `uav_modules/installation/install.sh` and `catkin clean` and `catkin build` in all the workspaces.

**Comment by pritzvac** [comment]
Hmm, something like this used to happen when we were building our packages with the `-march=native` flag, causing some incompatibilities with the PCL library...

Did you select to "Build PCL from sources" when running the install script for uav_modules, by any chance? It would probably create a `PCL_CROSS_COMPILATION` variable in your `.bashrc` file. Is there anything like that in your .bashrc?

**Comment by dorian21b** [comment]
I didn't select "build PCL from sources". I checked the `.bashrc` file and there is nothing like that.

**Comment by pritzvac** [comment]
Ok, I'm not sure where the problem comes from, since it looks like the issue where something is compiled with `-march=native`, causing memory errors, but your setup looks correct. (we have moved away from using it quite some time ago https://github.com/ctu-mrs/mrs_uav_system/issues/126 so if you have a clean install, it shouldn't be a problem...)

Anyway, I'd try reinstalling the PCL libraries, with something like
`sudo apt remove ros-noetic-pcl-*`
and then
`sudo apt install ros-noetic-pcl-ros ros-noetic-pcl-conversions`

Or you can try to build the PCL from sources using the [install_pcl.sh](https://github.com/ctu-mrs/mrs_pcl_tools/blob/master/install/install_pcl.sh) script. Just set `BUILD_WITH_MARCH_NATIVE` to `false` before you run it.

Or you can try to use the [singularity](https://github.com/ctu-mrs/mrs_singularity/) instead of native installation. It might be faster to set up than finding the cause of this issue.

**Comment by dorian21b** [comment]
Hello,
I tried to reinstall the PCL libraries but it did nothing more. then I try to build it from sources but I got the same result. At least I can sometimes run the simulation thanks to the debugger.

**Comment by klaxalk** [comment]
Hey, with the [new system](https://github.com/ctu-mrs/mrs_uav_system) out, you can install our [Octomap Mapping Planning](https://github.com/ctu-mrs/mrs_octomap_mapping_planning) package already pre-compiled and working.
```bash
curl https://ctu-mrs.github.io/ppa-stable/add_ppa.sh | bash
sudo apt install ros-noetic-mrs-uav-system-full
```
